In [8]:
# Numpy Array Formation 

import numpy as np 
arr = np.array(arr)
print(arr.ndim)   #n Dimensions
print(arr.shape)  # Dataset Shape: rows,columns
print(arr)        # Print : Array

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [7]:
#2D array 

arr1 = [[1,2,3],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [9]:
#3D Array

arr2 = [[[1,2,3,],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [10]:
#Matrix summation 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

c = a+b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [11]:
# diagonal matrix

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)

d = a + c 
print(d)


[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

z = b+e
print(z)

[[11. 21. 31.]
 [41. 51. 61.]
 [71. 81. 91.]]


In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [16]:
a*[2,3,4]


array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [17]:
# Changing Dtype :Datatype

a = np.array([1,2,3],dtype = 'float')
print (a)

[1. 2. 3.]


In [18]:
a = np.array([0,2,3], dtype = 'bool')
a

array([False,  True,  True])

In [19]:
a = np.array([0,2,3],dtype = 'complex')


In [20]:
# Arange Function 
# np.arange(start,stop,step)

a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [21]:
num = np.arange(0,20)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
num.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
num.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [24]:
num.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [25]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [26]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [27]:
a = np.linspace(0,20,10)
print(a.size)
a

10


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [28]:
num = np.arange(0,30)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
arr = num.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
arr.max(),arr.min(),arr.mean(),arr.std()

(29, 0, 14.5, 8.65544144839919)

In [31]:
n = np.arange(50,100) #1D
m = n.reshape(10,5)  #2D
print(m.ndim)  #checking dimension :2D
m[1:3,1:3]
m

2


array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [32]:
m[6:9,1:4]

array([[81, 82, 83],
       [86, 87, 88],
       [91, 92, 93]])

In [33]:
n = np.arange(101,131,dtype='float')
o = n.reshape(1,6,5) #3D
print(o.ndim) #checking Dimension :3D
o

3


array([[[101., 102., 103., 104., 105.],
        [106., 107., 108., 109., 110.],
        [111., 112., 113., 114., 115.],
        [116., 117., 118., 119., 120.],
        [121., 122., 123., 124., 125.],
        [126., 127., 128., 129., 130.]]])

In [34]:
#Slicing
o[3:,3:]

array([], shape=(0, 3, 5), dtype=float64)